'use client'

import { useState } from 'react'
import { createAnnualReport, updateAnnualReport, deleteAnnualReport } from '@/server/actions/annualReports'
import { AnnualReport } from '@prisma/client'

export default function AddAnnualReportDialog({
    entityId,
    report,
    hasRecurringAnnualReport = false,
    recurringReportFrequency = 'ANNUAL',
    recurringReportDueMonth = null,
    recurringReportDueDay = null
}: {
    entityId: string,
    report?: AnnualReport,
    hasRecurringAnnualReport?: boolean,
    recurringReportFrequency?: string | null,
    recurringReportDueMonth?: number | null,
    recurringReportDueDay?: number | null
}) {
    const [isOpen, setIsOpen] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [isRecurring, setIsRecurring] = useState(hasRecurringAnnualReport)

    // An "expected" report is mathematically generated by the Dashboard, not tracked in the DB yet,
    // so we handle it as a "Create" rather than an "Update"
    const isExpectedRow = !!(report?.id?.startsWith('expected-'))
    const isEditing = !!report && !!report.id && !isExpectedRow

    async function handleSubmit(formData: FormData) {
        setError(null)
        formData.append('entityId', entityId)

        // If it was an "Expected" report, Zod will fail if we pass the mock 'expected-uuid' string. 
        // We shouldn't need to append an ID at all for a Create action anyway.

        const action = isEditing
            ? updateAnnualReport.bind(null, report!.id)
            : createAnnualReport

        const result = await action(null, formData)

        if (result && !result.success) {
            setError(result.message || 'Failed to save report')
            return
        }

        setIsOpen(false)
    }

    async function handleDelete() {
        if (!report || !confirm('Are you sure you want to delete this report?')) return
        setError(null)
        const result = await deleteAnnualReport(report.id, entityId)
        if (result && !result.success) {
            setError(result.message || 'Failed to delete report')
            return
        }
        setIsOpen(false)
    }

    return (
        <>
            <button
                className={(isEditing || isExpectedRow) ? "btn btn-secondary" : "btn btn-primary"}
                onClick={() => setIsOpen(true)}
                style={(isEditing || isExpectedRow) ? { padding: "0.25rem 0.5rem", fontSize: "0.75rem" } : {}}
            >
                {(isEditing || isExpectedRow) ? 'Edit' : 'Add Report'}
            </button>

            {isOpen && (
                <div className="modal-backdrop" onClick={() => setIsOpen(false)}>
                    <div className="modal-content" onClick={e => e.stopPropagation()}>
                        <div className="modal-header">
                            <h2 className="modal-title">{(isEditing || isExpectedRow) ? 'Edit Annual Report' : 'Add Annual Report'}</h2>
                            <button className="modal-close" onClick={() => setIsOpen(false)}>×</button>
                        </div>

                        <form action={handleSubmit}>
                            {error && <div style={{ padding: '0.75rem', marginBottom: '1rem', fontSize: '0.875rem', color: '#991b1b', backgroundColor: '#fee2e2', borderRadius: '0.5rem', border: '1px solid #fecaca' }}>{error}</div>}

                            <div className="form-group">
                                <label>Year</label>
                                <input
                                    name="year"
                                    required
                                    defaultValue={report?.year || new Date().getFullYear().toString()}
                                    pattern="\d{4}"
                                    title="Four digit year"
                                    placeholder="YYYY"
                                />
                            </div>

                            <div className="form-group">
                                <label>Status</label>
                                <select name="status" defaultValue={report?.status || 'PENDING'}>
                                    <option value="PENDING">Pending</option>
                                    <option value="FILED">Filed</option>
                                    <option value="OVERDUE">Overdue</option>
                                    <option value="EXEMPT">Exempt</option>
                                </select>
                            </div>

                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                                <div className="form-group">
                                    <label>Due Date</label>
                                    <input
                                        type="date"
                                        name="dueDate"
                                        defaultValue={report?.dueDate ? new Date(report.dueDate).toISOString().split('T')[0] : ''}
                                    />
                                </div>
                                <div className="form-group">
                                    <label>Filing Date</label>
                                    <input
                                        type="date"
                                        name="filingDate"
                                        defaultValue={report?.filingDate ? new Date(report.filingDate).toISOString().split('T')[0] : ''}
                                    />
                                </div>
                            </div>

                            <div className="form-group">
                                <label>Document URL</label>
                                <input
                                    type="url"
                                    name="documentUrl"
                                    defaultValue={report?.documentUrl || ''}
                                    placeholder="https://..."
                                />
                            </div>

                            <div className="form-group">
                                <label>Notes</label>
                                <textarea
                                    name="notes"
                                    defaultValue={report?.notes || ''}
                                    rows={3}
                                />
                            </div>

                            <hr style={{ margin: "1.5rem 0", borderColor: "var(--border)" }} />

                            <h3 style={{ fontSize: "1rem", marginBottom: "1rem" }}>Recurrence Settings</h3>
                            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                                <input
                                    type="checkbox"
                                    id={`hasRecurringAnnualReport-${report?.id || 'new'}`}
                                    name="hasRecurringAnnualReport"
                                    checked={isRecurring}
                                    onChange={(e) => setIsRecurring(e.target.checked)}
                                    style={{ width: 'auto' }}
                                />
                                <label htmlFor={`hasRecurringAnnualReport-${report?.id || 'new'}`} style={{ margin: 0, cursor: 'pointer' }}>Make this a recurring requirement</label>
                            </div>

                            {isRecurring && (
                                <div style={{ background: "var(--muted)", padding: "1rem", borderRadius: "var(--radius)", marginBottom: "1rem" }}>
                                    <div className="form-group">
                                        <label>Frequency</label>
                                        <select name="recurringReportFrequency" defaultValue={recurringReportFrequency || 'ANNUAL'}>
                                            <option value="ANNUAL">Annual</option>
                                            <option value="BIANNUAL">Biannual</option>
                                            <option value="QUARTERLY">Quarterly</option>
                                            <option value="MONTHLY">Monthly</option>
                                        </select>
                                    </div>
                                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
                                        <div className="form-group" style={{ marginBottom: 0 }}>
                                            <label>Due Month (1-12)</label>
                                            <input
                                                type="number"
                                                name="recurringReportDueMonth"
                                                required={isRecurring}
                                                min="1"
                                                max="12"
                                                defaultValue={recurringReportDueMonth || ''}
                                                placeholder="Ex: 4 for April"
                                            />
                                        </div>
                                        <div className="form-group" style={{ marginBottom: 0 }}>
                                            <label>Due Day (1-31)</label>
                                            <input
                                                type="number"
                                                name="recurringReportDueDay"
                                                required={isRecurring}
                                                min="1"
                                                max="31"
                                                defaultValue={recurringReportDueDay || ''}
                                                placeholder="Ex: 15"
                                            />
                                        </div>
                                    </div>
                                </div>
                            )}

                            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '1.5rem' }}>
                                {isEditing ? (
                                    <button type="button" onClick={handleDelete} style={{ color: "red", background: "none", border: "none", cursor: "pointer", textDecoration: "underline" }}>
                                        Delete Report
                                    </button>
                                ) : (
                                    <div />
                                )}
                                <div style={{ display: 'flex', gap: '0.75rem' }}>
                                    <button type="button" className="btn btn-secondary" onClick={() => setIsOpen(false)}>Cancel</button>
                                    <button type="submit" className="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </>
    )
}
